#Defining persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
#Defining db deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:14.4  # Sets Image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432  # Exposes container port
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistence-storage
      volumes:
        - name: postgres-persistence-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim