#spring:
#  r2dbc:
#   url: r2dbc:postgresql://${DB_HOST}:5432/postgres?currentSchema=${DB_NAME}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}

# uncomment below to run at local
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?currentSchema=todoApp
    username: postgres
    password: mysecretpassword
